### PR TITLE
fix missing argument to load method of Loader

### PR DESCRIPTION
**Pull request by michaellopez**
When recording is enabled and a graphql request comes in that should be persisted, the call to `load` (to see whether the query id already exists or not) does not have the correct amount of arguments. The call needs to pass the operation name to `load`.

This PR fixes this and adds a test for it. Let me know if you would like me to take a different approach to the test, specifically the `enableRecording()`/`resetRecording()` setup. Wasn't sure how you wanted to handle database mutations for the unit tests @esamattis

### CODE REVIEW

**Comment by michaellopez** [comment]
@esamattis Oh right, also the functional tests don't work. It's the functional tests that are failing in the automated tests. I'm assuming it is out of scope for this issue to fix that.

**Comment by michaellopez** [comment]
@esamattis Sorry to bother you, any chance of getting this merged soon?

**Comment by esamattis** [comment]
Yeah, the functional test issue is unrelated. Merged in cleaned up commit in https://github.com/valu-digital/wp-graphql-lock/commit/3f0a3ee7c88eb8556c9b608cdf9ce3b00824de77 and released in 0.1.4

**Comment by michaellopez** [comment]
@esamattis Thank you!

**Pull request closed without merging**
